// qwik/src/routes/frameworks/layout.tsx
import { component$, Slot } from "@builder.io/qwik";
import { Link, routeLoader$, useLocation } from "@builder.io/qwik-city";
import { Button } from "~/components/button/button";
import { Card } from "~/components/card/card";
import { FrameworkListItem } from "~/components/framework-list-item/framework-list-item";
import { PanelHeader } from "~/components/panel-header/panel-header";
import { WorkflowContainer } from "~/components/workflow-container/workflow-container";
import { WorkflowPanel } from "~/components/workflow-panel/workflow-panel";
import database from "~/lib/db";
import { delay } from "~/lib/delay";

export const useFrameworks = routeLoader$(async () => {
  const frameworks = await delay(database.getFrameworks({}), 0);
  return frameworks;
});

export default component$(() => {
  const loc = useLocation();
  const frameworks = useFrameworks();
  return (
    <WorkflowContainer>
      <WorkflowPanel>
        <Card>
          <PanelHeader q:slot="header">Frameworks</PanelHeader>
          <div class="flex flex-1 justify-end gap-2" q:slot="header">
            <Link href="/frameworks/new">
              <Button variant="primary">ADD</Button>
            </Link>
          </div>
          <div class="flex h-full flex-col">
            <div class="static flex-1 overflow-auto border-b-2 border-t-2 border-solid border-indigo-50">
              {frameworks.value.map((framework) => (
                <FrameworkListItem
                  key={framework.id}
                  framework={framework}
                  selected={`${framework.id}` === loc.params.id}
                />
              ))}
            </div>
          </div>
          <span q:slot="footer">
            <>{frameworks.value.length} frameworks loaded</>
          </span>
        </Card>
      </WorkflowPanel>
      <Slot />
    </WorkflowContainer>
  );
});

// next-js/app/frameworks/[id]/detail/layout.tsx
import Card from "@/lib/components/ui/card";
import PanelHeader from "@/lib/components/ui/panel-header";
import PrimaryButton from "@/lib/components/ui/primary-button";
import SecondaryButton from "@/lib/components/ui/secondary-button";
import WorkflowPanel from "@/lib/components/workflow-panel";
import database from "@/lib/db";
import Link from "next/link";

export default async function FrameworkDetailLayout({
  children,
  params: { id },
}: {
  children: React.ReactNode;
  params: { id: number };
}) {
  const framework = (await database.getFramework(id))!;
  return (
    <>
      <WorkflowPanel>
        <Card
          header={
            <>
              <PanelHeader>{framework.name}</PanelHeader>
              <div className="flex-1 flex justify-end">
                <Link href={`/frameworks/${framework.id}/edit`}>
                  <PrimaryButton>EDIT</PrimaryButton>
                </Link>
              </div>
            </>
          }
          footer={
            <div className="flex justify-end">
              <Link href="/frameworks">
                <SecondaryButton>BACK</SecondaryButton>
              </Link>
            </div>
          }
        >
          <div className="flex flex-col h-full">
            <div className="flex flex-col flex-1 gap-6 px-4 overflow-auto">
              <div className="flex flex-col justify-between gap-2">
                <div className="font-semibold">Name</div>
                <div className="p-1 border-solid border rounded-md border-black dark:border-white">
                  {framework.name}
                </div>
              </div>
              <div className="flex flex-col justify-between gap-2">
                <div className="font-semibold">Description</div>
                <div className="p-1 h-[6.5rem] overflow-auto border-solid border rounded-md border-black dark:border-white">
                  {framework.description}
                </div>
              </div>
              <div className="flex flex-row items-center gap-4 text-xl pointer-events-none">
                <input
                  className="w-8 h-8"
                  type="checkbox"
                  checked={framework.isPoop || undefined}
                  readOnly
                />
                <div className="font-semibold">&#x1F4A9;?</div>
              </div>
            </div>
          </div>
        </Card>
      </WorkflowPanel>
      {children}
    </>
  );
}
