// next-js/app/frameworks/new/page.tsx
import FrameworkForm from "@/lib/components/framework-form";
import Card from "@/lib/components/ui/card";
import PanelHeader from "@/lib/components/ui/panel-header";
import PrimaryButton from "@/lib/components/ui/primary-button";
import SecondaryButton from "@/lib/components/ui/secondary-button";
import WorkflowPanel from "@/lib/components/workflow-panel";
import Link from "next/link";
import { createFramework } from "../actions";

export default function NewFrameworkPage() {
  return (
    <WorkflowPanel>
      <Card header={<PanelHeader>New Framework</PanelHeader>}>
        <FrameworkForm
          action={createFramework}
          footerActions={
            <div className="flex gap-4">
              <SecondaryButton>
                <Link href="/frameworks">CANCEL</Link>
              </SecondaryButton>
              <PrimaryButton>SAVE</PrimaryButton>
            </div>
          }
        ></FrameworkForm>
      </Card>
    </WorkflowPanel>
  );
}

// svelte-kit/src/routes/frameworks/new/+page.svelte
<script>
	import { goto } from '$app/navigation';
	import Card from '$lib/components/ui/Card.svelte';
	import FrameworkForm from '$lib/components/FrameworkForm.svelte';
	import WorkflowPanel from '$lib/components/WorkflowPanel.svelte';
</script>

<WorkflowPanel routeId="/frameworks/new">
	<Card>
		<h5 class="panel-header" slot="header">New Framework</h5>
		<FrameworkForm action="?/create" slot="body">
			<svelte:fragment slot="footer-actions">
				<button class="btn-secondary mr-4" on:click|preventDefault={() => goto('/frameworks')}
					>CANCEL</button
				>
				<button class="btn-primary">SAVE</button>
			</svelte:fragment>
		</FrameworkForm>
	</Card>
</WorkflowPanel>
