// nuxt/components/workflow/WorkflowPanel.vue
<script setup lang="ts">
const { name } = defineProps<{ name: string }>();
const route = useRoute();
const depth = computed(() => [...route.matched].reverse().findIndex((m) => m.name === name));
</script>

<template>
  <div
    class="contents"
    :data-panel-depth="depth"
  >
    <slot />
  </div>
</template>

// svelte-kit/src/lib/components/WorkflowPanel.svelte
<script>
	import { page } from '$app/stores';

	/** @type {string} */
	export let routeId;

	/** @type {import('$lib/active-route').ActiveRoute[]}*/
	$: activeRoutes = $page.data.activeRoutes;
	$: depth = activeRoutes.length - activeRoutes.findIndex((ar) => ar.routeId === routeId) - 1;
</script>

<div class="contents" data-panel-depth={depth}>
	<slot />
</div>
