// svelte-kit/src/lib/components/ui/Card.svelte
<script></script>

<div
	class=" w-full border rounded-lg shadow bg-zinc-800 border-zinc-700 max-w-screen-md flex-1 flex flex-col"
>
	{#if $$slots.header}
		<header class="flex items-center gap-4 p-4">
			<slot name="header" />
		</header>
	{/if}
	<main class="flex flex-col flex-auto overflow-auto">
		<slot name="body" />
	</main>
	{#if $$slots.footer}
		<footer class="p-4">
			<slot name="footer" />
		</footer>
	{/if}
</div>

// next-js/lib/components/ui/card.tsx
export default function Card({
  header,
  children,
  footer,
}: {
  header?: React.ReactNode;
  children: React.ReactNode;
  footer?: React.ReactNode;
}) {
  return (
    <div className="w-full bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-900 dark:border-gray-700 max-w-screen-md flex-1 flex flex-col">
      {header ? (
        <header className="flex items-center gap-4 p-4">{header}</header>
      ) : null}
      <main className="flex flex-col flex-auto overflow-auto">{children}</main>
      {footer ? <footer className="p-4">{footer}</footer> : null}
    </div>
  );
}
