// qwik/src/components/defer/defer.tsx
import { Slot, component$, useSignal, useTask$ } from "@builder.io/qwik";

export interface DeferProps {
  delay?: number;
}

export const Defer = component$<DeferProps>(({ delay = 500 }) => {
  const show = useSignal(false);

  useTask$(({ cleanup }) => {
    const handle = setTimeout(() => (show.value = true), delay);
    cleanup(() => clearTimeout(handle));
  });

  return show.value && <Slot />;
});

// next-js/lib/components/ui/defer.tsx
"use client";

import { useEffect, useState } from "react";

export default function Defer({
  children,
  delay = 500,
}: {
  children: React.ReactNode;
  delay?: number;
}) {
  const [show, setShow] = useState(false);

  useEffect(() => {
    const handle = setTimeout(() => setShow(true), delay);

    return () => clearTimeout(handle);
  }, [delay]);
  return <>{show ? children : null}</>;
}
