// qwik/src/components/card/card.tsx
import { Slot, component$, useStyles$ } from "@builder.io/qwik";

export interface CardProps {}

export const Card = component$<CardProps>(() => {
  useStyles$(CSS);
  return (
    <div class="flex w-full max-w-screen-md flex-1 flex-col rounded-lg border border-indigo-900 bg-indigo-950 shadow">
      <header class="card-header flex items-center gap-4 p-4">
        <Slot name="header" />
      </header>

      <main class="flex flex-auto flex-col overflow-auto">
        <Slot />
      </main>
      <footer class="card-footer p-4">
        <Slot name="footer" />
      </footer>
    </div>
  );
});

export const CSS = `
.card-header:empty {
  display: none;
}

.card-footer:empty {
  display: none;
}
`;

// svelte-kit/src/lib/components/ui/Card.svelte
<script></script>

<div
	class=" w-full border rounded-lg shadow bg-zinc-800 border-zinc-700 max-w-screen-md flex-1 flex flex-col"
>
	{#if $$slots.header}
		<header class="flex items-center gap-4 p-4">
			<slot name="header" />
		</header>
	{/if}
	<main class="flex flex-col flex-auto overflow-auto">
		<slot name="body" />
	</main>
	{#if $$slots.footer}
		<footer class="p-4">
			<slot name="footer" />
		</footer>
	{/if}
</div>
