// next-js/lib/workflow/breadcrumbs.tsx
"use client";

import type { Route } from "next";
import Link from "next/link";
import { useWorkflowContext } from "./workflow-provider";

function Breadcrumb({
  label,
  path,
  end,
}: {
  label: string;
  path: Route;
  end?: boolean;
}) {
  if (end) {
    return <span className="font-bold">{label}</span>;
  }
  return (
    <>
      <Link href={path as Route}>{label}</Link>
      <span>{">"}</span>
    </>
  );
}

export default function Breadcrumbs() {
  const { workflow } = useWorkflowContext()!;
  const last = workflow.length - 1;
  return (
    <div className="flex-none flex gap-4 p-4 overflow-auto">
      <Breadcrumb label={"HOME"} path="/" />
      {workflow.map(({ label, path }, i) => (
        <Breadcrumb key={path} label={label} path={path} end={i === last} />
      ))}
    </div>
  );
}

// svelte-kit/src/lib/components/frame/Breadcrumbs.svelte
<script>
	/** @type {import('$lib/active-route').ActiveRoute[]}*/
	export let activeRoutes;
</script>

<div class="flex-none flex gap-4 p-4 overflow-auto">
	{#each activeRoutes as { path, routeId, title }, i (routeId)}
		{#if i < activeRoutes.length - 1}
			<a href={path}>{title}</a>
			<span>{'>'}</span>
		{:else}
			<span class="font-bold">{title}</span>
		{/if}
	{/each}
</div>
