// next-js/app/frameworks/[id]/(detail)/layout.tsx
import Card from "@/lib/components/ui/card";
import PanelHeader from "@/lib/components/ui/panel-header";
import WorkflowPanel from "@/lib/workflow/workflow-panel";
import { getFramework } from "../get-framework";
import { Route } from "next";
import { Suspense } from "react";
import LoadingFramework from "../loading-framework";
import Button from "@/lib/components/ui/button";
import WorkflowLink from "@/lib/workflow/workflow-link";

export default async function FrameworkDetailLayout({
  children,
  params: { id },
}: {
  children: React.ReactNode;
  params: { id: number };
}) {
  return (
    <>
      <WorkflowPanel label="Framework" path={`/frameworks/${id}` as Route}>
        <Suspense fallback={<LoadingFramework />}>
          <FrameworkDetail id={id} />
        </Suspense>
      </WorkflowPanel>
      {children}
    </>
  );
}

async function FrameworkDetail({ id }: { id: number }) {
  const framework = await getFramework(id);
  return (
    <Card>
      <Card.Header>
        <PanelHeader>{framework.name}</PanelHeader>
        <div className="flex-1 flex justify-end">
          <WorkflowLink href={`/frameworks/${framework.id}/edit`}>
            <Button variant="primary">EDIT</Button>
          </WorkflowLink>
        </div>
      </Card.Header>
      <Card.Body>
        <div className="flex flex-col h-full">
          <div className="flex flex-col flex-1 gap-6 px-4 overflow-auto">
            <div className="flex flex-col justify-between gap-2">
              <div className="font-semibold">Name</div>
              <div className="p-1 border-solid border rounded-md border-black dark:border-white">
                {framework.name}
              </div>
            </div>
            <div className="flex flex-col justify-between gap-2">
              <div className="font-semibold">Description</div>
              <div className="p-1 h-[6.5rem] overflow-auto border-solid border rounded-md border-black dark:border-white">
                {framework.description}
              </div>
            </div>
            <div className="flex flex-row items-center gap-4 text-xl pointer-events-none">
              <input
                className="w-8 h-8"
                type="checkbox"
                checked={framework.isPoop || undefined}
                readOnly
              />
              <div className="font-semibold">&#x1F4A9;?</div>
            </div>
          </div>
        </div>
      </Card.Body>
      <Card.Footer>
        <div className="flex justify-end">
          <WorkflowLink href="/frameworks">
            <Button variant="secondary">BACK</Button>
          </WorkflowLink>
        </div>
      </Card.Footer>
    </Card>
  );
}

// qwik/src/routes/frameworks/layout.tsx
import { component$, Slot } from "@builder.io/qwik";
import { Link, routeLoader$, useLocation } from "@builder.io/qwik-city";
import { Button } from "~/components/button/button";
import { Card } from "~/components/card/card";
import { FrameworkListItem } from "~/components/framework-list-item/framework-list-item";
import { PanelHeader } from "~/components/panel-header/panel-header";
import { WorkflowContainer } from "~/components/workflow-container/workflow-container";
import { WorkflowPanel } from "~/components/workflow-panel/workflow-panel";
import database from "~/lib/db";
import { delay } from "~/lib/delay";

export const useFrameworks = routeLoader$(async () => {
  const frameworks = await delay(database.getFrameworks({}), 0);
  return frameworks;
});

export default component$(() => {
  const loc = useLocation();
  const frameworks = useFrameworks();
  return (
    <WorkflowContainer>
      <WorkflowPanel>
        <Card>
          <PanelHeader q:slot="header">Frameworks</PanelHeader>
          <div class="flex flex-1 justify-end gap-2" q:slot="header">
            <Link href="/frameworks/new">
              <Button variant="primary">ADD</Button>
            </Link>
          </div>
          <div class="flex h-full flex-col">
            <div class="static flex-1 overflow-auto border-b-2 border-t-2 border-solid border-indigo-50">
              {frameworks.value.map((framework) => (
                <FrameworkListItem
                  key={framework.id}
                  framework={framework}
                  selected={`${framework.id}` === loc.params.id}
                />
              ))}
            </div>
          </div>
          <span q:slot="footer">
            <>{frameworks.value.length} frameworks loaded</>
          </span>
        </Card>
      </WorkflowPanel>
      <Slot />
    </WorkflowContainer>
  );
});
