// svelte-kit/src/lib/components/PanelHeader.svelte
<script>
	/**
	 * @typedef {Object} Props
	 * @property {import('svelte').Snippet} children
	 */

	/** @type {Props} */
	let { children } = $props();
</script>

<h5
	class="panel-header mb-2 pb-1 border-b-4 border-transparent text-2xl font-bold tracking-tight text-white"
>
	{@render children()}
</h5>

// qwik/src/components/panel-header/panel-header.tsx
import { Slot, component$ } from "@builder.io/qwik";

export interface PanelHeaderProps {}

export const PanelHeader = component$<PanelHeaderProps>(() => {
  return (
    <h5 class="panel-header mb-2 border-b-4 border-transparent pb-1 text-2xl font-bold tracking-tight text-white">
      <Slot />
    </h5>
  );
});
