// next-js/app/dashboard/page.tsx
import Link from "next/link";

export default function Dashboard() {
  return (
    <div className="flex flex-1 gap-x-4 gap-y-4 overflow-auto p-4 items-center justify-center w-full">
      <ul className="list-disc list-inside">
        <li className="border-l-4 border-transparent data-[active]:border-sky-500 hover:dark:bg-gray-700">
          <Link className="cursor-pointer ml-1" href="/frameworks">
            Frameworks
          </Link>
        </li>
      </ul>
    </div>
  );
}

// nuxt/pages/dashboard.vue
<script setup lang="ts">
definePageMeta({ name: 'Dashboard' });
</script>

<template>
  <div class="flex flex-1 gap-x-4 gap-y-4 overflow-auto p-4 items-center justify-center w-full">
    <ul class="list-disc list-inside">
      <li class="border-l-4 border-transparent hover:dark:bg-emerald-700">
        <NuxtLink
          class="cursor-pointer ml-1"
          to="/frameworks"
        >
          Frameworks
        </NuxtLink>
      </li>
    </ul>
  </div>
</template>
