// remix/lib/ui/WorkflowPanel.tsx
type WorkflowPanelProps = {
  //  label: string;
  // path: Route;
  children: React.ReactNode;
};

export default function WorkflowPanel({
  children,
}: // label,
// path,
WorkflowPanelProps) {
  // const depth = useWorkflowEntry({ label, path });

  return (
    <div className="contents" data-panel-depth={0}>
      {children}
    </div>
  );
}

// nuxt/components/workflow/WorkflowPanel.vue
<script setup lang="ts">
const { name } = defineProps<{ name: string }>();
const route = useRoute();
const depth = computed(() => [...route.matched].reverse().findIndex((m) => m.name === name));
</script>

<template>
  <div
    class="contents"
    :data-panel-depth="depth"
  >
    <slot />
  </div>
</template>
